export const SET_SOURCE_CONNECTOR_ID = 'SET_SOURCE_CONNECTOR_ID';
export const SET_DEST_CONNECTOR_ID = 'SET_DEST_CONNECTOR_ID';
export const SET_PROJECT_ID = 'SET_PROJECT_ID';
export const SET_CONTAINER_NAME = 'SET_CONTAINER_NAME';
export const SET_CONNECTION_STRING = 'SET_CONNECTION_STRING';
export const SET_KEY_FILE = 'SET_KEY_FILE';
export const SET_JOBS = 'SET_JOBS';